server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=UTC
    username: root
    password: "Liang.13"
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  mail:
    host: smtp.qq.com
    port: 587
    username: 2715072505@qq.com
    password: xgaegymcokhvdfbi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.example.baken: debug
    org.example.baken.mapper: DEBUG
    org.mybatis: DEBUG

jwt:
  secret: "your-secret-key" # JWT 密钥
  expiration: 86400000 # JWT 过期时间（单位：毫秒，默认 24 小时）

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: org.example.baken.entity

