server:
  port: 8080

spring:
  datasource:
    url: 你的mysql地址
    username: 你的数据库用户名
    password: 你的数据库用户密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  mail:
    host: smtp.qq.com（你的邮箱host）
    port: 587
    username:你的邮箱用户
    password: 你的邮箱密码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.example.baken: debug
    org.example.baken.mapper: DEBUG
    org.mybatis: DEBUG

jwt:
  secret: "your-secret-key" # JWT 密钥
  expiration: 86400000 # JWT 过期时间（单位：毫秒，默认 24 小时）

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: org.example.baken.entity

